/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_PERPUSTAKAAN;

/**
 *
 * @author ASUS TUF GAMING
 */
public class siswa extends javax.swing.JFrame {

    /**
     * Creates new form siswa
     */
    public siswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dasbord = new javax.swing.JButton();
        data_anggota = new javax.swing.JButton();
        data_buku = new javax.swing.JButton();
        peminjaman = new javax.swing.JButton();
        pengembalian = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 900));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jButton1.setText("PROFIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(940, 110, 120, 40);

        dasbord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        dasbord.setText("DASBORD");
        dasbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasbordActionPerformed(evt);
            }
        });
        getContentPane().add(dasbord);
        dasbord.setBounds(20, 190, 170, 60);

        data_anggota.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        data_anggota.setText("DATA ANGGOTA");
        data_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(data_anggota);
        data_anggota.setBounds(20, 270, 170, 60);

        data_buku.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        data_buku.setText("DATA BUKU");
        data_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_bukuActionPerformed(evt);
            }
        });
        getContentPane().add(data_buku);
        data_buku.setBounds(20, 350, 170, 60);

        peminjaman.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        peminjaman.setText("PEMINJAMAN");
        peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(peminjaman);
        peminjaman.setBounds(20, 430, 170, 60);

        pengembalian.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        pengembalian.setText("PENGEMBALIAN");
        pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(pengembalian);
        pengembalian.setBounds(20, 510, 170, 60);

        jToggleButton2.setText("LOGOUT");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(10, 800, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 710, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/halaman.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        profil m = new profil();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianActionPerformed
        pengembalian m = new pengembalian();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pengembalianActionPerformed

    private void peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanActionPerformed
        peminjaman m = new peminjaman();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_peminjamanActionPerformed

    private void data_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_bukuActionPerformed
        buku m = new buku();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_data_bukuActionPerformed

    private void data_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_anggotaActionPerformed
        siswa m = new siswa();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_data_anggotaActionPerformed

    private void dasbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasbordActionPerformed
        dasbord m = new dasbord();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dasbordActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dasbord;
    private javax.swing.JButton data_anggota;
    private javax.swing.JButton data_buku;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton peminjaman;
    private javax.swing.JButton pengembalian;
    // End of variables declaration//GEN-END:variables
}
